[package]
name = "csaps"
version = "0.1.0"
authors = ["Eugene Prilepin <esp.home@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
ndarray = "0.13"
sprs = "0.7.1"
